name: tencent_map
description: Tencent Map SDK for Flutter
version: 0.0.1
homepage: https://github.com/qiuxiang/flutter-tencent-map

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^3.1.3

flutter:
  plugin:
    platforms:
      android:
        package: qiuxiang.tencent_map
        pluginClass: TencentMapPlugin
      ios:
        pluginClass: TencentMapPlugin
